@startuml
!theme vibrant
object IRCTC_Customer {
    IRCTC Customer
}

object Complaint_Portal {
    Complaint Portal
}

object Authentication_Gateway {
    Authentication Gateway
}

object Complaint_Gateway {
    Complaint Gateway
}

object Authentication_Database {
    Authentication Database
}

object Complaint_Database {
    Complaint Database
}

object Batch_Processing_Unit {
    Batch Processing Unit
}

IRCTC_Customer --> Complaint_Portal : Create a new Customer Account
Complaint_Portal --> Authentication_Gateway : Add a new Customer Entity to Authentication Records
Authentication_Gateway --> Authentication_Database : INSERT Customer Details INTO Database
Authentication_Database --> Authentication_Gateway : Customer Insertion Successful
Authentication_Gateway --> Complaint_Portal : Customer Insertion Successful
Complaint_Portal --> IRCTC_Customer : Account Created

IRCTC_Customer --> Complaint_Portal : Register a new Complaint
Complaint_Portal --> Complaint_Gateway : Add a new Complaint Entity to the Records
Complaint_Gateway --> Complaint_Database : INSERT Complaint Details INTO Database
Complaint_Database --> Complaint_Gateway : Complaint Insertion Successful
Complaint_Gateway --> Complaint_Portal : Complaint Entity with updated fields returned
Complaint_Portal --> IRCTC_Customer : Complaint Registered

Complaint_Database --> Batch_Processing_Unit : SELECT all un-assigned Complaint Entities
Batch_Processing_Unit --> Complaint_Database : Process content, categorize, assign department & officer, modify list
Batch_Processing_Unit --> Complaint_Database : UPDATE un-assigned Complaint Entities SET Department and Officers
Complaint_Database --> Batch_Processing_Unit : Complaint Records Updated

Complaint_Portal --> IRCTC_Customer : Check the Status of the Complaint
Complaint_Gateway --> Complaint_Database : SELECT the Complaint Entity
Complaint_Database --> Complaint_Gateway : Complaint Entity returned
Complaint_Gateway --> Complaint_Portal : Complaint Entity with updated fields returned
Complaint_Portal --> IRCTC_Customer : Latest Complaint with updated status and messages returned

@enduml
