@startuml
!theme vibrant
actor "IRCTC Passenger"
actor "IRCTC Officer"

"IRCTC Passenger" --> (Web Application)
"IRCTC Officer" --> (Web Application)

(Web Application) --> (Complaint Registration Service)
(Web Application) --> (User Authentication Service)
(Complaint Registration Service) --> (Scheduled Categorization Service)

(User Authentication Service) --> (Database)
(Scheduled Categorization Service) --> (Database)

(Complaint Registration Service) --> "Database"

node "Database" {
}
@enduml
