@startuml
!theme vibrant

actor "IRCTC Passenger"
actor "IRCTC Complaint Officer"

"IRCTC Passenger" --> (Login)
"IRCTC Passenger" --> (Register / Create Account)

(Login) --> (See Messages from Officer)
(Login) --> (Register Complaint)

(Register Complaint) --> (Submit Complaint)

(Register / Create Account) --> (Submit Complaint)

(View Assigned Complaints) --> (Process Complaint)

"IRCTC Complaint Officer" --> (View Assigned Complaints)
"IRCTC Complaint Officer" --> (Process Complaint)
"IRCTC Complaint Officer" --> (Update Status)
"IRCTC Complaint Officer" --> (Resolved)

(Process Complaint) --> (Update Status)
(Process Complaint) --> (Resolved)

"Schedule Categorization Service" --> (Issue Fixed)
"Schedule Categorization Service" --> (Keyword Analysis)
"Schedule Categorization Service" --> (Categorize Complaint)

(Keyword Analysis) --> (Categorize Complaint)
(Categorize Complaint) --> (Assign To Officer)

(Issue Fixed) --> (Resolved)

@enduml
