name: Format, Lint & Test Java files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 15 * * 4'

jobs:
  format_lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '22'
      - name: Format Java files
        run: mvn -f pom.xml spotless:check
      - name: Lint Java files
        run: mvn -f pom.xml checkstyle:check
      - name: Run Tests
        run: mvn -f pom.xml clean test
